[#109] YDSTooltip (툴팁)
yourssu/YDS-iOS pull request #124
Opened 2022-04-07 12:26 UTC by lygon55555

## 📌 Summary

툴팁을 개발했습니다.

## 💡 Reason

사용자가 뷰에 진입했을 때 도움말이나 정보, 위치 등을 사용자에게 소개하고 안내해주기 위해서 개발했습니다.

## ✍️ Description

- 이슈 티켓 : #109
- 피그마 : https://www.figma.com/file/0u52cd50xDQqjanMpUvUOM/%5B1.-iOS%5D-Yourssu-Design-System?node-id=4227%3A2114
- 관련 문서 : [Tooltip 문서](https://yourssu.notion.site/Tooltip-5c208827cbfc41d696bf51e11b386afc)  
[YDSTooltip 문서](https://yourssu.notion.site/YDSTooltip-ded15e3556c84784ae784c0c8bb5f1e6)

## 🔥 Test

https://user-images.githubusercontent.com/39911797/162198244-1c2ed02f-9d23-4c5e-89a5-78cd266482a0.mp4

2022-04-08 08:32 UTC, JunsangKwon approved these changes
수고하셨습니다~~~

2022-04-08 08:32 UTC, JunsangKwon commented on YDS/Source/Component/YDSTooltip.swift
> +            let point1 = CGPoint(x: tailPosition == .left ? 0 : self.frame.size.width,
self.frame.size.width, self.frame.size.height를 변수로 따로 빼고 사용해도 좋을 것 같습니다!

2022-04-10 07:58 UTC, Gyuni requested changes

2022-04-10 07:58 UTC, Gyuni commented on YDS/Source/Component/YDSTooltip.swift
> +            self.backgroundColor = color == .tooltipBG ? YDSColor.tooltipBG : YDSColor.tooltipPoint
`p3`
이 부분은 괄호를 치거나 if-else 문 혹은 if + early return 문으로 가독성을 개선하면 좋을 것 같습니다
https://gomjellie.github.io/%ED%8C%A8%ED%84%B4/2020/04/27/early-return.html

저기 아래쪽의 path 만드는 부분도 삼항연산자가 주로 쓰이고 있는데 괄호를 쳐서 가독성을 개선하면 좋을 것 같습니다

2022-04-10 07:58 UTC, Gyuni commented on YDS/Source/Component/YDSTooltip.swift
> +    }()
`p3`
툴팁이 아닌 영역을 터치했을 때 화면을 닫아주기 위해 이러한 UIView를 만들고 UITapRecognizer를 달아주셨는데
UITapRecognizer과 UIView 대신 UIControl만 넣어주고 UIControl의 event를 구독하는 식으로 하는 편은 어떨까요?
작성해주신 방법이 절대 틀린 방법은 아니지만, 다른 구현 방법도 있을 것 같아 제안드려 봅니다
둘 중 코드가 더 간결해지는 방향으로 하면 좋을 것 같네요

2022-04-10 07:58 UTC, Gyuni commented on YDS/Source/Component/YDSTooltip.swift
> +            makeTail()
`p4`
makeTail() 대신 setNeedsLayout() 을 호출해 layoutSubviews() 이 불리도록 하면 어떨까요?
이 편이 조금 더 확실할 것 같습니다
사실 제가 기존에 작성한 YDS 코드들도 이렇게 처리하도록 했어야 한다는 아쉬움도 있습니다

2022-04-10 07:58 UTC, Gyuni commented on YDS/Source/Component/YDSTooltip.swift
> +            makeTail()
https://www.sungdoo.dev/programming/layout-driven-ui/

2022-04-10 07:58 UTC, Gyuni commented on YDS/Source/Component/YDSTooltip.swift
> +        }
`p2`
makeTail의 로직이
1. sublayer의 첫 번째가 CAShapeLayer라면 해당 layer를 제거 (tailLayer를 제거하기 위한 동작)
2. 포지션에 따라 새로운 tailLayer를 만듦
3. 새로운 tailLayer를 sublayer로 추가

인 상황인데, 만약 sublayer의 첫 번째 layer가 CAShapeLayer이지만 tailLayer가 아니라면 문제가 생길 수 있습니다
이 문제를 해결하기 위해 YDSToolTip 클래스의 프로퍼티로 `private var tailLayer: CAShapeLayer?` 를 따로 관리하고
makeLayer 할 때 tailLayer?.removeFromSuperlayer() 해주고, 다시 새로운 레이어가 만들어지면 이곳에 할당해주는 편이 오작동을 방지할 수 있을 것 같습니다

2022-04-10 08:02 UTC, Gyuni commented on YDS/Source/Component/YDSTooltip.swift
> +        }
<img width="574" alt="스크린샷 2022-04-10 오후 5 01 26" src="https://user-images.githubusercontent.com/54972653/162608625-6e9afe58-aadf-4807-ab38-28e228a64ef0.png">

이 부분은은 profileview에 비슷한 코드가 있는데 참고 부탁드립니당

2022-04-12 13:05 UTC, lygon55555 commented
스토리북에 맞추느라 로직 수정된 거 + 규니님 리뷰 반영해서 다시 작업할게요!

2022-04-14 13:54 UTC, lygon55555 commented on YDS/Source/Component/YDSTooltip.swift
> +            self.backgroundColor = color == .tooltipBG ? YDSColor.tooltipBG : YDSColor.tooltipPoint
곰젤리님 블로그군요 ㅋㅋㅋㅋㅋㅋㅋ

2022-04-14 13:55 UTC, lygon55555 commented on YDS/Source/Component/YDSTooltip.swift
> +            self.backgroundColor = color == .tooltipBG ? YDSColor.tooltipBG : YDSColor.tooltipPoint
컴파일 속도면에서는 if문보다 삼항연산자가 더 빠른 거로 알고 있긴 한데
처음보는 사람한테는 헷갈릴 수 있으니까 괄호를 사용해서 가독성을 높여볼게요

2022-04-14 13:57 UTC, lygon55555 commented on YDS/Source/Component/YDSTooltip.swift
> +            makeTail()
> `p4` makeTail() 대신 setNeedsLayout() 을 호출해 layoutSubviews() 이 불리도록 하면 어떨까요? 이 편이 조금 더 확실할 것 같습니다 사실 제가 기존에 작성한 YDS 코드들도 이렇게 처리하도록 했어야 한다는 아쉬움도 있습니다

제가 나중에 여유되면 다른 YDS 코드들도 수정해볼게요

2022-04-17 12:20 UTC, closed without merging